This branch is to refactor classes in OOP School Library project
steveWDamesJr/oop-school-library pull request #7
Opened 2022-06-20 15:20 UTC by steveWDamesJr

## Refactor Classes

:sunglasses: This is @steveWDamesJr 's  and @levy002 's 1st group milestone for the OOP-School-Library build. :sunglasses:

- [x] Ensure that YAGNI, KISS, and DRY rules and Ruby style guide are respected
- [x] Follow SOLID principles.
- [x] Adhere to "Single-responsiblity Principle":
        - Ensure that the role of `main.rb` is only to start our code and ask the user for the initial  choice of options (or to quit).
        - Extract some pieces of logic into separate class(es).

- [ ] Debug linters

   
    

![Refactor](https://media.giphy.com/media/LqmVGgvWmGWvG4Rv0t/giphy.gif)

Thank you for taking the time to review our PR :pray:

2022-06-20 17:31 UTC, FrederickMih requested changes
Hi Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/nYYtQdLqwwlTe3ccKh/giphy.gif)

# To Highlights

- PR has a title and good summary :heavy_check_mark: 
- GitHub workflow has been followed :heavy_check_mark: 
- Linters checks are passing :heavy_check_mark: 
- README file is descriptive :heavy_check_mark: 

## Required Changes ♻️

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-20 17:31 UTC, FrederickMih commented on app.rb
>      if @user_input == '1'
- [x] Hi team, you guys are doing so great on this project :+1: . All requests for inputs and input validation should've been placed in the main.rb file and/or classes/methods whose responsibilities are to request or validate input hence this is a bad example of a single responsibility rule. Let's kindly refactor this again.
- [Best Practices lesson](https://github.com/microverseinc/curriculum-ruby/blob/main/oop/lessons/solid.md#best-practices-and-solid)

2022-06-21 10:40 UTC, levy002 commented on app.rb
>      if @user_input == '1'
Thank you @FrederickMih for the excellent suggestions. We've implemented it.

2022-06-21 10:44 UTC, Temmarie approved these changes
# Status: Approved ✔️ 
## Hi @steveWDamesJr  and @levy002  , 
### Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### Congratulations! 🎉 

#### Cheers and Happy coding!👏👏👏

#### Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
------
_As described in the [Code reviews limits policy](<https://microverse.zendesk.com/hc/en-us/articles/1500004088561>) you have a limited number of code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](<https://airtable.com/shrQAqnBwek5a0O0s>)._

2022-06-21 10:47 UTC, merged